### ISSUE TITLE
Review what output memory area should contain in case of failures in EEI methods

### ISSUE THREAD

**Issue by axic** [ewasm/design#123]
Sparked by a discussion in https://github.com/ewasm/design/pull/76#discussion_r206594988

**Comment by lrettig** [comment]
When in doubt I'd prefer to err on the side of safety, given that this is Ethereum, and to me safety here means zeroing it out. This forces the developer to always be explicit.

**Comment by axic** [comment]
@chfast @holiman can you please raise your voices here?

**Comment by chfast** [comment]
I'm for leaving the memory untouched in case of failure.

Let's consider example methods:

```cpp
bool get_something(int* output);
void do_something(int);
```

In case of option where the output is zeroed on failure, the following use cases are valid:

```cpp
void use_case_1() {
    int x;
    if (get_something(&x))
        do_something(x);
}

void use_case_2() {
    int x;
    get_something(&x);
    do_something(x);
}
```

In case of option where the output is untouched, the `use_case_2()` is invalid and can be easily detected by static analysis tools. However the `use_case_2()` can be changed into a valid one by initializing `int x = 0`.

I would specify that the error code returned from methods SHOULD be checked. That would be "in text" equivalent of `warn_unused_result` function annotation in C/C++.

**Comment by holiman** [comment]
I would (tentatively) be for @lrettig 's suggestion. 

> When in doubt I'd prefer to err on the side of safety, given that this is Ethereum, and to me safety here means zeroing it out. This forces the developer to always be explicit.

Perhaps @chfast can expand a bit on the reasoning above, not sure I understand the implications of those examples.

**Comment by axic** [comment]
Can you point to an EEI method which can fail but has no means to signal that?

**Comment by jakelang** [comment]
@axic i guess i forgot `getBlockHash` has a return value. I still don't see any particular security benefits from zeroing out all the output memory on failure, especially if the EEI method can signal failure using the return code already.

**Comment by axic** [comment]
I agree with @chfast and @jakelang's point so will close this issue now, meaning everything stays as is.
