### ISSUE TITLE
querry

### ISSUE THREAD

**Issue by aj07** [ewasm/design#160]
Is there any place where grammar rules for ewasm are defined? I am trying to build package around it.

**Comment by lrettig** [comment]
It sounds like you're looking for the [main Wasm spec](https://github.com/WebAssembly/spec). Ewasm has no grammar rules aside from the Wasm grammar.

**Comment by aj07** [comment]
@lrettig I wanted to build the atom package library for ewasm. There I needed grammar. Does, wasm grammar fits there?
