### ISSUE TITLE
New EEI method: abort

### ISSUE THREAD

**Issue by axic** [ewasm/design#43]
Abort execution and store a reason.

**Parameters**
- `reasonCode` **i32** the reason code
- `descriptionOffset` **i32** the memory offset to load the reason text from
- `descriptionLength` **i32** the length of the reason text (limited to 32 bytes)

**Returns**

_nothing_

**Comment by axic** [comment]
Related https://github.com/ethereum/EIPs/issues/62. It could also be replaced with special `LOGs`, which are not rolled back at execution errors.

**Comment by wanderer** [comment]
why not just use `return`?

**Comment by axic** [comment]
Assuming we change return so that the value is not rolled back on a VM error that could work. However that introduces a discrepancy with how EVM expects it.

**Comment by axic** [comment]
Solved by https://github.com/ethereum/EIPs/blob/master/EIPS/eip-140.md
