### ISSUE TITLE
Specify a license for this repo

### ISSUE THREAD

**Issue by axic** [ewasm/design#53]
Probably Apache 2.0 makes sense given its consideration for patents.

(Also webassembly/design uses Apache 2.0.)

@wanderer @gcolvin are you fine with Apache 2.0? It is only three of us as contributors to this repo so far.

**Comment by wanderer** [comment]
lgtm;

**Comment by gcolvin** [comment]
That would be fine by me,  though since there is no code here the patent protections in the Apache license are irrelevant.  I'd be happy with public domain for that matter.

**Comment by axic** [comment]
I think the Apache 2.0 patent clauses not only apply to code and also this repo contains interfaces and in some cases code too.

**Comment by gcolvin** [comment]
Apache is fine by me.
    
    
    On 10/8/16 10:46 AM, Alex Beregszaszi
      wrote:
    
    
      I think the Apache 2.0 patent clauses not only apply to code
        and also this repo contains interfaces and in some cases code
        too.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ewasm/design","title":"ewasm/design","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ewasm/design"}},"updates":{"snippets":[{"icon":"PERSON","message":"@axic in #53: I think the Apache 2.0 patent clauses not only apply to code and also this repo contains interfaces and in some cases code too."}],"action":{"name":"View Issue","url":"https://github.com/ewasm/design/issues/53#issuecomment-252435081"}}}

**Comment by gcolvin** [comment]
Gosh, replying via email sure makes a mess when it gets here.  Apache is fine by me.

**Comment by gcolvin** [comment]
Testing stripped down plain text reply.  Excuse the noise.

**Comment by gcolvin** [comment]
Test succeeded, so Github discussions can be integrated into my email workflow.  Yes!

**Comment by axic** [comment]
Fixed by #57.
