### ISSUE TITLE
selfDestruct clarification

### ISSUE THREAD

**Issue by pepyakin** [ewasm/design#72]
Continue of discussion started [here](https://github.com/ewasm/design/commit/02fad14d9e4025d7996626480dc835e62a2d07d9#diff-0ef45ade35525c1f5658644b501c426b):

@pepyakin :

> What does it mean "the contract shall halt execution after this call"? Is it means that contract code is supposed to some how return control after calling selfDestruct? What if it doesn't do so? Why just don't trap?

@axic :

> Next time please open an issue on the repo - it is way harder to track it that way.
>
> It just means that effectively selfDestruct is just a marking for deletion a buffer. Any subsequent calls overwrite that buffer. Any successful halt will enforce the selfdestruct.
>
> Combining it with a trap would put the condition detection onus no the VM implementation - not all (especially browser) VMs make that easy.

Hm, I had an impression that VMs should usually provide a way to trap from the inside of the host function with the ability to distingish between different host traps.

For example, binaryen implements traps [with exceptions](https://github.com/WebAssembly/binaryen/blob/3d8358f8e10a01869ef59189539ab1d17d52cb10/src/shell-interface.h#L185), you can just implement `selfDestruct` to trap with a special string or just throw your own exception. WAVM is also lets you do the same by [throwing](https://github.com/AndrewScheidecker/WAVM/blob/45153136ced537f97eb8ed4635fdcc0b71b54ae1/Include/Runtime/Runtime.h#L177) and [catching](https://github.com/AndrewScheidecker/WAVM/blob/45153136ced537f97eb8ed4635fdcc0b71b54ae1/Include/Runtime/Runtime.h#L180) exceptions, which [possibly created by the embedder](https://github.com/AndrewScheidecker/WAVM/blob/45153136ced537f97eb8ed4635fdcc0b71b54ae1/Include/Runtime/Runtime.h#L165).

As for browser trapping inside the browser definitely possible! traps can be implemented by JS exceptions and JS exceptions are easy to discriminate.

For example, this is how `abort` implemented in expiremental wasm musl implementation.

- here is definition of [`TerminateWasmException`](https://github.com/jfbastien/musl/blob/dbd68988a813727678d4b93cfd818b5622230dd9/arch/wasm32/wasm.js#L69)
- upon a call to [`abort`](https://github.com/jfbastien/musl/blob/dbd68988a813727678d4b93cfd818b5622230dd9/arch/wasm32/wasm.js#L466) this exception is thrown.
- the code of main start executing [here](https://github.com/jfbastien/musl/blob/dbd68988a813727678d4b93cfd818b5622230dd9/arch/wasm32/wasm.js#L1478) in a try block.
- `TerminateWasmException` is caught [here](https://github.com/jfbastien/musl/blob/dbd68988a813727678d4b93cfd818b5622230dd9/arch/wasm32/wasm.js#L1486)

So it seems easy to me. Maybe I misunderstood you? 

And about the current approach: 
what should happen, if contract called `selfDestruct` and then tried to touch the storage (read or write), call to a create `create` or `*call`?

**Comment by axic** [comment]
A quick update on this:
1) The above question applies to `selfdestruct`, `revert` and `return`
2) Pretty much everyone is in favour of termination, we just want to make sure "exception throwing" is possible in every VM. (cc @ehildenb)

[invocation](https://webassembly.github.io/spec/core/exec/modules.html#invocation):
> Invocation may fail with an error if the arguments do not fit the function type. Invocation can also result in a trap. It is up to the embedder to define how such conditions are reported.

The spec is somewhat loose on this, but as you said it is possible to catch it in Javascript, Binaryen, wavm and probably in wabt. Not sure about wagon (well, its a now at the moment there, cc @gballet).

**Comment by ehildenb** [comment]
I'm in favor of forced traps (instead of relying on the code to force a trap after a call to selfDestruct). I don't think it would be hard to add this functionality to any VMs which don't have it. One argument (which may not be important) would be that by forcing people to supply code to force a trap after `selfDestruct`, you'll be making the effective cost of calling `selfDestruct` higher (simply because the program will be larger and metering deployment will be more expensive).

I don't think I'm in favor of "labelled" or "typed" traps being available inside the VM itself, because the spec has nothing dealing with that and execution halts immediately. If you're referring to the embedder having access to information about what supplied the trap, that seems fine to me.

**Comment by pepyakin** [comment]
> I don't think it would be hard to add this functionality to any VMs which don't have it. 

Host functions might be viewed as an ordinary functions, and ordinary function can either return a result or trap. There is no reason for a general wasm implementation to not allow this.

> I don't think I'm in favor of "labelled" or "typed" traps being available inside the VM itself, because the spec has nothing dealing with that and execution halts immediately. If you're referring to the embedder having access to information about what supplied the trap, that seems fine to me.

Yep, you right, the spec doesn't specify anything about traps except that they abort the further execution. But because wasm allows embedder to implement host functions (or even, without support host functions wasm would be quite limited), and assuming that the implementation doesn't support typing/labelling exception, in the worst case you can emulate trap discrimination via saving a global a-lá `errno`.

But personally I'm quite sure that the most of implementations supports and will support trap discrimination in one way or another.

**Comment by pepyakin** [comment]
The alternative solution (quite conservative though) for trapping might be to implement transformation that injects `unreachable` after each EEI call that traps:

E.g

```WebAssembly
;; ...
call $ethereum.return
```

→ 

```WebAssembly
;; ...
call $ethereum.return
unreachable
```

**Comment by axic** [comment]
Yeah that might be a workaround, though currently `unreachable` is considered as an execution failure.

I like having the ethereum calls trapping properly, just like certain syscalls do, such as exit.

**Comment by ehildenb** [comment]
I would rather not instrument the code more than necessary if most existing embedders are able to do trap discrimination. I showed an example of how we could clarify these in issues #89.

Basically, if we do something like `errno`, I don't think that even belongs in the wasm VM itself (in the example above, I add the EEI state explicitly as an `EEI` fragment of the configuration). If calling the `useGas` function leads to an out-of-gas exception, I think it's up to the embedder/client to determine what that means to do next, not the VM. The VM is just the portion of the client that enables arbitrary computation, but it shouldn't be responsible for any logic regarding *what* computation to perform.

**Comment by pepyakin** [comment]
Yeah, definitely agree! As I said: I'm quite convinced that VM impls are able to provide means to discriminate between different kind traps. And this alternative solution is just to show that this is still possible.

But, I didn't meant to add `errno` meachnism to the VM (in fact, to be clear, I actually strongly against any modifications on the VM level). I meant that this EEI funcs upon a call will change the host-defined state (e.g `EEI.gasAvailable` mentioned by you).

**Comment by chfast** [comment]
In EVM1 the `SELFDESTRUCT` transfers ETH immediately. The EEI document states that the transfer is done after the execution.
