### ISSUE TITLE
Clarification of SelfDestruct: multiple invocations will overwrite the benficiary address.

### ISSUE THREAD

**Issue by maurelian** [ewasm/design#86]
From here: https://github.com/ewasm/design/blob/master/eth_interface.md#selfdestruct

I don't understand what this means:

> Note: multiple invocations will overwrite the benficiary address.

Does it mean the beneficiary changes to the address specified by the most recent `SELFDESTRUCT` call? 

Testing in remix, it seems the first address is the  beneficiary.

**Comment by chfast** [comment]
In EVM there is no way to execute selfdestruct twice, because the first one ends the execution.

**Comment by maurelian** [comment]
Then what does it mean to have multiple invocations?

**Comment by chfast** [comment]
Nothing useful. The second one is unreachable.

**Comment by axic** [comment]
#72 should solve this
